import React from 'react'
import { Container, Row, Col, Form } from 'react-bootstrap';
import { BsFillCheckCircleFill } from 'react-icons/bs';
import { FaThumbsUp } from 'react-icons/fa'
function ValidateContract() {
  return (
    <>
      <section className='validateContract_wrap'>
        <Container>
          <Row className='justify-content-center'>
            <Col lg={12}>
              <div className='validate_contract_form'>
                <div className='debug_text'>Compiler debug log:</div>
                <div className='validate_contract_note'>
                  <BsFillCheckCircleFill /> Note: Contract was created during TxHash# <a href='#'>0x8916ff0459a54e0a9fb7419f5ff4d62499c198b5</a>
                </div>
                <div className='validate_contract_success_note'>
                  <FaThumbsUp /> Succecssfully generated Bytecode and ABI for Contract Address <a href='#'>[0x6ff0459a54e0a9fb7419f5ff4d62499c198b5]</a>
                </div>
                <div className='validate_contract_address_div'>
                  <div className='compiler'><strong>Compiler Version:</strong> v0.8.7+commit.e28d00a7</div>
                  <div className='compiler'><strong>Optimization Enabled:</strong> 0</div>
                  <div className='compiler'><strong>Runs:</strong> 200</div>


                  <Form.Group className='contract_name mt-4'>
                    <Form.Label>Contract Name:</Form.Label>
                    <Form.Control type="text" />
                  </Form.Group>

                  <Form.Group className='contract_bytecode mt-2'>
                    <Form.Label>ContractByteCode:</Form.Label>
                    <Form.Control as="textarea" />
                  </Form.Group>

                  <Form.Group className='contract_abi mt-2'>
                    <Form.Label>ContractABI:</Form.Label>
                    <Form.Control as="textarea" />
                  </Form.Group>
                  </div>





              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </>
  )
}

export default ValidateContract
